import type { LandingDict } from "./types";

export const en: LandingDict = {
  meta: {
    title: "RandoRank — Every trail becomes a challenge",
    description:
      "The fun, community-driven hiking app: challenges, leaderboards and badges for walkers and hikers.",
  },
  header: {
    openMenu: "Open menu",
    closeMenu: "Close menu",
    menuLabel: "Menu",
    login: "Log in",
    signup: "Sign up",
    language: "Language",
    links: {
      ranking: "Leaderboard",
      navigation: "Navigation",
      offers: "Plans",
      faq: "FAQ",
      spots: "Spots & community",
      follow: "Follow us",
    },
  },
  hero: {
    badge: "🥾 Join the RandoRank community",
    titleLine1: "Every trail",
    titleLine2: "becomes a challenge.",
    subtitle:
      "Track your hikes, unlock new badges, climb the leaderboard and share your best outings.",
    ctaPrimary: "Create my profile",
    ctaSecondary: "I already have an account",
    imageAlt: "Hiker on a mountain ridge facing the peaks",
  },
  spots: {
    eyebrow: "Spots & community",
    title: "Your spots. Your landmarks.",
    text: "Forest, alpine lake or a summit push with friends: discover the spots shared by the community and meet the hikers who watch the same sunrises as you.",
    items: [
      {
        alt: "Hiker on a forest trail facing the mountains",
        title: "Woodland",
        caption: "Shaded trails",
      },
      {
        alt: "Hiker facing an alpine lake surrounded by snowy peaks",
        title: "Alpine lake",
        caption: "Turquoise water",
      },
      {
        alt: "Group of hikers on a trail leading to a rocky summit",
        title: "Summits in sight",
        caption: "Among hikers",
      },
    ],
  },
  share: {
    eyebrow: "Show off your feats",
    titleLine1: "A stylish card.",
    titleLine2: "Ready for your stories.",
    text: "At the end of every hike, RandoRank automatically generates a visual card with your route, your stats and your best photos — made for Instagram, TikTok and Facebook, not for gathering dust in a drawer.",
    shareOn: "Share on",
    cta: "Create my first card",
    floatingTap: { label: "In one tap", value: "Ready to share" },
    floatingUnlocked: { label: "Unlocked", value: "Devil's Peak" },
    imageAlt: "Hike card generated by RandoRank, ready to share",
    date: "12 Jun 26",
    routeName: "Three Peaks Ridge",
    stats: [
      { v: "14.2", u: "km" },
      { v: "+680", u: "m gain" },
      { v: "4h05", u: "time" },
    ],
  },
  route: {
    eyebrow: "Generate your route",
    titleLine1: "Tell us your distance.",
    titleLine2: "RandoRank handles the rest.",
    text: "Enter the distance you're up for — and your goal, if you have one. RandoRank suggests a route you can actually walk, then adjusts it to your level and the health information in your profile, so you get a trail that fits you rather than a generic itinerary.",
    cta: "Plan my route",
    floatingRoute: { label: "Route generated", value: "12 km" },
    floatingElevation: { label: "Max elevation gain", value: "+450 m" },
    level: "Amateur level",
    start: "Start",
    end: "Finish",
    mapAlt: "Map excerpt, Chamonix area",
    distance: "Distance",
    distanceValue: "12 km",
    duration: "Estimated time",
    durationValue: "3h15",
    startCta: "Start the hike",
  },
  ranking: {
    eyebrow: "Leaderboard",
    titleLine1: "Every kilometre",
    titleLine2: "counts.",
    text: "The kilometres you really walk move you up. Follow your position on the leaderboard, unlock badges and beat your own goals — or your friends'.",
    floatingPosition: { label: "Your position", value: "#3" },
    floatingNext: { label: "To pass #2", value: "6.4 km" },
    month: "Leaderboard · September 2026",
    tabs: { national: "National", region: "Region", friends: "Friends" },
    you: "You",
    kms: ["58.1 km", "48.5 km", "42.0 km", "39.7 km"],
  },
  community: {
    eyebrow: "Community on the move",
    title: "It's not just numbers.",
    text: "It's every kilometre actually walked and validated by all RandoRank hikers.",
    kmLabel: "Walked by the community",
    elevationLabel: "Of total elevation gain",
    chartLabel: "Kilometres per week, whole community",
  },
  offers: {
    eyebrow: "Plans",
    title: "Le MUL. Period.",
    text: "One plan, everything included: unlimited hikes, routes and photos, the full leaderboard. Pricing details appear as soon as you create your profile.",
    cta: "Create my profile",
  },
  about: {
    eyebrow: "RandoRank in a few words",
    text: "RandoRank helps you plan hiking routes that match your level, share your passion and discover new spots. Record every route, analyse your hikes and compare yourself with friends and with every hiker on the site — by region, by département, all the way up to the national level.",
  },
  faq: {
    eyebrow: "Everything's clear",
    title: "Frequently asked questions",
    items: [
      {
        question: "Does RandoRank cost anything?",
        answer:
          "Yes: RandoRank works on a Premium subscription only (monthly or yearly, cancel any time). You get access to everything: unlimited hikes and routes, photos, national and regional leaderboards, badges — pricing details are shown when you create your profile.",
      },
      {
        question: "How does route generation work?",
        answer:
          "You tell us the distance you want to cover (and optionally a starting point or a maximum elevation gain). RandoRank suggests a route you can actually walk, then refines it to your level and the health information you enter in your profile, so you get a trail that fits you rather than a plain generic itinerary.",
      },
      {
        question: "Are my stats public?",
        answer:
          "Your detailed stats stay private and mainly help you analyse your own progress. Only validated kilometres appear on the public leaderboard, so you can compare your progress with other hikers without exposing the details of your outings.",
      },
      {
        question: "How are kilometres validated?",
        answer:
          "Every imported or recorded track goes through consistency checks: plausible speed, continuity over time, elevation that matches the terrain, and teleport detection. The goal: a leaderboard that reflects real hikes, not doctored files.",
      },
    ],
    disclaimer:
      "RandoRank gives you reference points, not mountain safety instructions: always check the weather and your own abilities before setting out.",
  },
  finalCta: {
    title: "Ready for your first challenge?",
    text: "Join the hikers who track, share and progress together.",
    cta: "Create my profile",
    imageAlt: "Forest trail leading towards the mountains",
  },
  footer: {
    tagline:
      "The hiker's logbook: outings, challenges and leaderboards among enthusiasts.",
    navTitle: "Navigation",
    nav: {
      routes: "Routes",
      analyses: "Insights",
      rankings: "Leaderboards",
      offers: "Plans",
      faq: "FAQ",
    },
    legalTitle: "Legal",
    legal: {
      notice: "Legal notice (FR)",
      privacy: "Privacy (FR)",
      cookies: "Cookies (FR)",
      terms: "Terms (FR)",
    },
    followTitle: "Follow us",
    rights: "All rights reserved.",
  },
};
